### ISSUE TITLE
Merge this repo into either eclipse.platform or eclipse.platform.ui?

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ua#163]
This seems to be one of the last separate code repos not considered for a merge, the build time is quite moderate with ~5minutes so it should not add much still the question would be

- merge to eclipse.platform?
- merge to eclipse.platform.ui?

@vogella @akurtakov @iloveeclipse @mickaelistria @..... what do you think?

**Comment by akurtakov** [comment]
I would vote for eclipse.platform in a separate ua folder - the whole jsp/jetty story makes it quite different from platform.ui for me.

**Comment by iloveeclipse** [comment]
I think eclipse.platform.ui would be the best fit here.

> the whole jsp/jetty story makes it quite different from platform.ui

Please could you elaborate how that is related to the repo merge?

**Comment by akurtakov** [comment]
> Please could you elaborate how that is related to the repo merge?

Sure, when repos are merged the goal is to merge things where they overlap most e.g. platform.text in platform.ui as platform.text is so deeply integrated with it and with nothing else.
In the platform.ua case - there are small UI parts that integrate with platform.ui but the real knowledge and development goes into developing the jsp/jetty parts, just like Ant integration which lives in eclipse.platform in ant subfolder.
Anyway, we seem to need more opinions here.

**Comment by laeubi** [comment]
For me the only thing would be that UA (=user assistance?) seems closer to UI (user interface), but from my side it does not matter too much so the question would be is there any compelling reason for your choice or would you be fine with the other way round as well?

And beside that, do we want to do it after M1 or do we need to wait for next release?

**Comment by merks** [comment]
> I would vote for eclipse.platform in a separate ua folder - the whole jsp/jetty story makes it quite different from platform.ui for me.

I would also vote for this.

**Comment by laeubi** [comment]
@iloveeclipse do you have any major concerns or would you also be fine with `eclipse.platform` even though you would prefer `eclipse.platform.ui`?

**Comment by iloveeclipse** [comment]
If Alex and Edd prefer platform, I'm OK with that.

**Comment by laeubi** [comment]
So question would be, should we do it now so to get it into M2?

**Comment by merks** [comment]
@laeubi 

Will this be the last merge for this release?   Are there others planned for the future?  (Thanks again for doing these things!)

**Comment by laeubi** [comment]
This is the last "platform" code repository I'm currently plan to merge (even though there is no "planning" at all) until we approach the final structure of having

- platform
- platform.ui

I also [recommended it for JDT](https://github.com/eclipse-jdt/eclipse.jdt.core/discussions/615) but  it does not feels something is happening there in the near future ...

**Comment by merks** [comment]
Then, personally, and this is "just my opinion", I think we should bite the bullet and get this done before M1 and be done with it!

**Comment by akurtakov** [comment]
Doing it for M1 would be nice, although it would be a very tight schedule.

**Comment by iloveeclipse** [comment]
Reopened:
- please delete content from old repo
- please migrate any bugs/prs from old repo
- finally: for all the merged repos in M1 please send a mail to platform dev list, because we saw already a case where committers wew not watching github and merged PR's into old repo.

**Comment by laeubi** [comment]
I have transferred the issues and notified on open PRs.

**Comment by merks** [comment]
The projects are imported from their new location/repository and are still in their "UA" working sets:

![image](https://github.com/eclipse-platform/eclipse.platform.ua/assets/208716/28cd74dd-0127-4339-93e7-ffb40d4e4c4e)

**Comment by iloveeclipse** [comment]
> * please delete content from old repo

@laeubi : can you please continue with that? Please also add readme file explaining where the code is gone.

**Comment by laeubi** [comment]
See here
- https://github.com/eclipse-platform/eclipse.platform.ua/pull/166

**Comment by laeubi** [comment]
Just some statistics after the merge:

```
[INFO] Average project wall time: 6.34s
[INFO] Total concurrency: 97%
```

That's not that bad, given the variations in the build times before the merge the new projects are not noticeably changed the build time in any way:

![grafik](https://github.com/eclipse-platform/eclipse.platform.ua/assets/1331477/d5fbd8c1-66bd-4ea6-b780-6a5c24c8066d)

**Comment by BeckerWdf** [comment]
Can this be closed?
