### ISSUE TITLE
Compiler warnings in ua.tests.doc

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.ua#63]
The following warning is reported in ua.tests.doc

<html>
<body>
<h4 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">/src/org/eclipse/ua/tests/doc/internal/linkchecker/ApiDocTest.java : 1 warning :</h4>

1. WARNING in /src/org/eclipse/ua/tests/doc/internal/linkchecker/ApiDocTest.java (at line 113)private static final Pattern NON_API_PACKAGES = Pattern.compile(".+\\.(?:internal\|tests\|examples)(?:\\..+)?");The value of the field ApiDocTest.NON_API_PACKAGES is not used
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by akurtakov** [comment]
Already fixed via https://github.com/eclipse-platform/eclipse.platform.ua/commit/21fad6cfaf945156a5b1ba4b797a58b6841eb9ea
