### ISSUE TITLE
5 HelpServer tests are failing in Jenkins

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ua#82]
Here is a dummy PR that shows the fails: https://github.com/eclipse-platform/eclipse.platform.ua/pull/81.

I've stumbled over them while changing completely unrelated code in https://github.com/eclipse-platform/eclipse.platform.ua/pull/77.

In official SDK tests the tests below succeed.
No idea what's wrong here, may be some maven/tycho specific issue (SDK tests run with ant).

[Test Result](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-81/1/testReport/) (5 failures )
[org.eclipse.ua.tests.help.webapp.HelpServerInterrupt.testServerWithInterrupt](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-81/1/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerInterrupt/testServerWithInterrupt/)
[org.eclipse.ua.tests.help.webapp.HelpServerInterrupt.testServerWithoutInterrupt](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-81/1/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerInterrupt/testServerWithoutInterrupt/)
[org.eclipse.ua.tests.help.webapp.HelpServerBinding.testStandaloneBinding](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-81/1/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerBinding/testStandaloneBinding/)
[org.eclipse.ua.tests.help.webapp.HelpServerBinding.testInfocenterBinding](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-81/1/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerBinding/testInfocenterBinding/)
[org.eclipse.ua.tests.help.webapp.HelpServerBinding.testWorkbenchBinding](https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/PR-81/1/testReport/junit/org.eclipse.ua.tests.help.webapp/HelpServerBinding/testWorkbenchBinding/)

First stack:
```
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:33771/help/index.jsp
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at org.eclipse.ua.tests.help.webapp.HelpServerInterrupt.checkServer(HelpServerInterrupt.java:114)
	at org.eclipse.ua.tests.help.webapp.HelpServerInterrupt.testServerWithInterrupt(HelpServerInterrupt.java:66)
```
**Update**

The tests started to fail in Jenkins on January 09, last good build was on December 21:
![image](https://user-images.githubusercontent.com/964108/212103547-1b02aab8-4de5-4125-b13b-c6838dbfd91a.png)

**Console logs good/bad**

- [consoleText_97_last_good.txt](https://github.com/eclipse-platform/eclipse.platform.ua/files/10403209/consoleText_97_last_good.txt)
- [consoleText_98_first_failing.txt](https://github.com/eclipse-platform/eclipse.platform.ua/files/10403211/consoleText_98_first_failing.txt)

**Comment by akurtakov** [comment]
Master build has been failing but no one noticed. I would say there should be notification emails send to platform-dev on master verification build failures for each git repo. WDYT?

**Comment by iloveeclipse** [comment]
> I would say there should be notification emails send to platform-dev on master verification build failures for each git repo. WDYT?

I've asked for that after this notification was removed (during one of many transitions from X to Y we had recently). I believe the answer was "feel free to contribute" :-)

If we could re-introduce test results mails (I believe they were send to platform-releng originally), and someone could contribute that, would be great.

**Comment by akurtakov** [comment]
FWIW, we never had master verification builds per repo like we have now. I think I can do this one. But the I-build tests is(at least was) far more convoluted for me to dedicate the time.

**Comment by iloveeclipse** [comment]
> we never had master verification builds per repo like we have now

I'm lost. What is "master verification build per repo"?

**Comment by akurtakov** [comment]
https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/master/

**Comment by iloveeclipse** [comment]
Interestingly, they run fine in SDK builds and also locally on my RHEL 7.9 in the IDE. 
@laeubi : did we had any mvn/tycho updates in the range (21.12 ; 09.01]?

**Comment by iloveeclipse** [comment]
I see the "good" console had following INFO reported, the "bad" one doesn't. Surefire version change?
```
[INFO] --- maven-surefire-plugin:3.0.0-M7:test (default-test) @ org.eclipse.ui.intro.quicklinks ---
[INFO] No tests to run.
```

**Comment by iloveeclipse** [comment]
Also the "good" build had these warnings / bad build don't have them.
```
[WARNING] Problems resolving provisioning plan.: [Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.extender; (&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0))).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.serviceloader; (osgi.serviceloader=org.slf4j.spi.SLF4JServiceProvider).]
[WARNING] Problems resolving provisioning plan.: [Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.extender; (&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0))).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.serviceloader; (osgi.serviceloader=org.slf4j.spi.SLF4JServiceProvider).]
[WARNING] Problems resolving provisioning plan.: [Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.extender; (&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0))).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.serviceloader; (osgi.serviceloader=org.slf4j.spi.SLF4JServiceProvider).]
[WARNING] Problems resolving provisioning plan.: [Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.extender; (&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0))).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.serviceloader; (osgi.serviceloader=org.slf4j.spi.SLF4JServiceProvider).]
[WARNING] Problems resolving provisioning plan.: [Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.extender; (&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0))).; Unable to satisfy dependency from org.slf4j.api 2.0.6 to osgi.serviceloader; (osgi.serviceloader=org.slf4j.spi.SLF4JServiceProvider).]
```

**Comment by laeubi** [comment]
@iloveeclipse I'm not specifically aware of any thing but you can browse the change history here:
https://github.com/eclipse-tycho/tycho/commits/master

**Comment by laeubi** [comment]
> No tests to run.

Just to be sure: Die the tests match the pattern `**/*Test.java` ?

**Comment by laeubi** [comment]
By the way I have reticently updated the docs with an additional section about testing including some demo projects:
https://tycho.eclipseprojects.io/doc/master/TestingBundles.html

so probably this can help you understand how testing with Tycho works, if not, please share what should/could be improved here or if anything is missing.

**Comment by akurtakov** [comment]
Fixed via https://github.com/eclipse-platform/eclipse.platform.ua/commit/91d18ce74dee3d2013cde63d11e0e3a0eeef0539
